### ISSUE TITLE
Create first version of slides

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#1]
For further discussion.

**Comment by fsteeg** [comment]
Basic intro, workshop structure, session times, and exercise format: http://lodworkshop.github.io/slides

**Comment by acka47** [comment]
I think this is a good basis for our discussion tomorrow.

One detail regarding the terminology:
I agree with the transparent & open post linked to on slides 3-5 but I am not sure whether we should use this terminology. In [LEM](https://www.penflip.com/lemanifesto/lemanifesto) we also talked about licensing, using "open" and "transparent" in another way as well as adding "inclusion" to the mix. We might want to stick to this terminology: being open, transparent and inclusionary. (Though I don't really like "inclusionary".)
