### ISSUE TITLE
Special design for exercises

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#14]
By now, we have a lot of slides and it will become even more. To improve understanding and naviagtion of the files, I think it would make sense to visually distinguish exercise slides from other slides. My proposal: Add a frame around the text for exercises. What do you think, @fsteeg ?

**Comment by fsteeg** [comment]
Sounds good, I'll look into that.

**Comment by acka47** [comment]
Resolved with https://github.com/hbz/swib16-workshop/pull/22/commits/d322d2803216d95c41cae38ce65c454018e254f5. Closing.
