### ISSUE TITLE
Add "further reading" slide

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#25]
In the end of the slide deck , we should add a slide with links for further reading. The list might include for example:

- [The state of the Octoverse 2016](https://octoverse.github.com/)
- [Git intro for librarians](http://data-lessons.github.io/library-git/)
- [Pro git](https://git-scm.com/book/en/v2)

**Comment by fsteeg** [comment]
Done, see https://hbz.github.io/swib16-workshop/#/21. Closing.
