### ISSUE TITLE
Send pre-workshop email to participants

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#3]
A week before the workshop we should send out an email to the participant. Contents:
- request to install git on their conference laptops and to create GitHub account
- ...tbc

**Comment by fsteeg** [comment]
An attempt for a complete list:
- Create an account on https://github.com/
- Install git: https://git-scm.com/downloads
- Install cURL: https://curl.haxx.se/download.html
- Install jq: https://stedolan.github.io/jq/

**Comment by acka47** [comment]
I created a first draft at http://etherpad.lobid.org/p/swib16-workshop-mail-ob4zg3cc.
