### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zuphilip** [hbz/swib16-workshop#31]
# Overall impression

For me, this workshop has been

- [x] very useful.
- [ ] interesting, but doesn't relate much to my daily work.
- [ ] dispensable.

# Things to improve

Just one comment: I suggest to do the readme exercise online on GitHub instead of on your local machine. Normally, GitHub is suggesting in the online repo to add a `README.md` automatically. Moreover, I think it is easier to handle the markup language there with the possibility to have a preview. Then, you could just continue by explaining to pull your repo to your local machine.

## Things that were missing

Automated software testing (e.g. TravisCI or CircleCI), Docker or some other third pary tools. I guess it would be enough to mention them and maybe show an example (personally my favourite example is "Sheldon"-bot in https://github.com/citation-style-language/styles/ which reacts on your PR).

## Things that were unnecessary

Personally, I think that for these small fixes the review functions are maybe a little overkill. Also it was (for me) not exactly clear how your two step approach work.

## Things I would have needed more time/explanation/examples to understand

More exercises especially group exercises would be great. Actually, I can't get enough exercises on such workshops...

## Things that needed less time to spend with

# Things I really liked about the workshop

I like to work with a specific project and to work in the group. It was interesting to tweak around with your API and the leaflet JavaScript library.

# More feedback

Great workshop! You should give the workshop at other opportunities to spread this open development thinking more.

**Comment by acka47** [comment]
Thank you very much for the feedback! We will definitely consider it when reworking the workshop for ELAG or whenever we will offer it again. Leaving this open until then.
