### ISSUE TITLE
Issue template for feedback

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#5]
Create an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) for participants to provide feedback during/after the workshop

**Comment by acka47** [comment]
I wouldn't use issues for inviting feedback in another workshop. But here, it probably makes sense to exemplify some possibilities on GitHub like issue template, check lists in markdown etc.

**Comment by fsteeg** [comment]
If you don't think it makes sense (why not?), we don't have to. We can show the issue template functionality in the actual project repo, where participants will open issues for bugs they find.

**Comment by acka47** [comment]
Actually, my problems addresses templates in general. it is a bit strange to see a text field pre-populated with some markdown. But I will probably get used to it.

We may adjust the current template later. Closing.
