### ISSUE TITLE
Choose other example for linked dev on GitHub

### ISSUE THREAD

**Issue by acka47** [hbz/swib16-workshop#9]
With https://github.com/hbz/swib16-workshop/commit/0c3f2758d30b5e1ef5e3d10d451fb4ce9a8c3187 an example was added for linked development on GitHub that might be improved.
To do: choose/create issue with mention, link to other issue and maybe link to a commit. Add a screenshot of the issue to the slides.

**Comment by acka47** [comment]
I am thinking of using an issue from this repo using the full potential for self-reference. Maybe #3 or – even better – this one? What do you think @fsteeg?

**Comment by fsteeg** [comment]
I'm fine with using this issue here, though I don't see the problem with the original sample.
